# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Python version
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py

# Define custom steps to install poetry and dependencies
build:
  jobs:
    post_create_environment:
      # Install poetry using pip
      - pip install poetry
    post_install:
      # Run poetry install within the virtual environment
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install
