name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # Also trigger on pull requests to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # The type of runner that the job will run on

    steps:
    - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx  # Install Sphinx
        pip install recommonmark  # If you are using Markdown
        pip install myst-parser  # For Markdown support
        pip install myst-nb  # For Jupyter Notebook support, includes myst-parser
        pip install sphinx sphinx-autoapi  # Add sphinx-autoapi here


    - name: Build documentation
      run: |
        cd docs
        make html  # Build your Sphinx documentation

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html  # The folder where Sphinx outputs the HTML files
